// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYaZo9tvbIjB550fzXH3oas3i5qJeV0n4',
    appId: '1:404766482833:web:c9e325fea8f8f775e13a30',
    messagingSenderId: '404766482833',
    projectId: 'ecoalerta-feb23',
    authDomain: 'ecoalerta-feb23.firebaseapp.com',
    storageBucket: 'ecoalerta-feb23.appspot.com',
    measurementId: 'G-T4Z7L2RV7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Q7D4fNCKqksPr2RBq0hzvdFRqOXIaJA',
    appId: '1:404766482833:android:745dc92df0ca786fe13a30',
    messagingSenderId: '404766482833',
    projectId: 'ecoalerta-feb23',
    storageBucket: 'ecoalerta-feb23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuyVbyLLhOBPYNbtLM_PP8zPpDhARnkBs',
    appId: '1:404766482833:ios:d89fca6cf6149a28e13a30',
    messagingSenderId: '404766482833',
    projectId: 'ecoalerta-feb23',
    storageBucket: 'ecoalerta-feb23.appspot.com',
    iosBundleId: 'com.example.ecoAlerta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuyVbyLLhOBPYNbtLM_PP8zPpDhARnkBs',
    appId: '1:404766482833:ios:f9dc8cd170f621ade13a30',
    messagingSenderId: '404766482833',
    projectId: 'ecoalerta-feb23',
    storageBucket: 'ecoalerta-feb23.appspot.com',
    iosBundleId: 'com.example.ecoAlerta.RunnerTests',
  );
}
